"""create timesheet periods

Revision ID: 2ebe9fa53315
Revises: 5a04bd448acf
Create Date: 2026-06-03 07:52:27.671091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ebe9fa53315'
down_revision: Union[str, None] = '5a04bd448acf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timesheet_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'pending_review', 'closed')", name='ck_period_status'),
    sa.CheckConstraint('month >= 1 AND month <= 12', name='ck_period_month_range'),
    sa.CheckConstraint('year >= 2000 AND year <= 2100', name='ck_period_year_range'),
    sa.ForeignKeyConstraint(['closed_by_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_period_department_year_month', 'timesheet_periods', ['department_id', 'year', 'month'], unique=False)
    op.create_index(op.f('ix_timesheet_periods_department_id'), 'timesheet_periods', ['department_id'], unique=False)
    op.create_index(op.f('ix_timesheet_periods_year'), 'timesheet_periods', ['year'], unique=False)
    # Partial unique indexes: NULL department_id treated separately (NULL != NULL in PG)
    op.execute("""
        CREATE UNIQUE INDEX uq_period_dept_year_month
        ON timesheet_periods (department_id, year, month)
        WHERE department_id IS NOT NULL
    """)
    op.execute("""
        CREATE UNIQUE INDEX uq_period_null_dept_year_month
        ON timesheet_periods (year, month)
        WHERE department_id IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timesheet_periods_year'), table_name='timesheet_periods')
    op.drop_index(op.f('ix_timesheet_periods_department_id'), table_name='timesheet_periods')
    op.drop_index('ix_period_department_year_month', table_name='timesheet_periods')
    op.drop_index('uq_period_null_dept_year_month', table_name='timesheet_periods')
    op.drop_index('uq_period_dept_year_month', table_name='timesheet_periods')
    op.drop_table('timesheet_periods')
    # ### end Alembic commands ###
