"""add is_active to references

Revision ID: 59a2b3cf4826
Revises: cee886016f5e
Create Date: 2026-06-02 15:17:43.839077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a2b3cf4826'
down_revision: Union[str, None] = 'cee886016f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('departments', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('schedules', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'is_active')
    op.drop_column('departments', 'is_active')
    op.drop_column('companies', 'is_active')
    # ### end Alembic commands ###
