"""create timesheet entries table

Revision ID: 5a04bd448acf
Revises: 74cf30a02e9b
Create Date: 2026-06-03 07:24:11.971081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a04bd448acf'
down_revision: Union[str, None] = '74cf30a02e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timesheet_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hours >= 0 AND hours <= 24', name='ck_timesheet_hours_range'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'work_date', 'company_id', name='uq_timesheet_employee_date_company')
    )
    op.create_index('ix_timesheet_employee_date', 'timesheet_entries', ['employee_id', 'work_date'], unique=False)
    op.create_index(op.f('ix_timesheet_entries_employee_id'), 'timesheet_entries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_timesheet_entries_work_date'), 'timesheet_entries', ['work_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timesheet_entries_work_date'), table_name='timesheet_entries')
    op.drop_index(op.f('ix_timesheet_entries_employee_id'), table_name='timesheet_entries')
    op.drop_index('ix_timesheet_employee_date', table_name='timesheet_entries')
    op.drop_table('timesheet_entries')
    # ### end Alembic commands ###
