"""add adjustments, loan fields and loan_deductions

Revision ID: 685b31c8afcc
Revises: c6d7e8f9a0b1
Create Date: 2026-06-19 16:23:50.858925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685b31c8afcc'
down_revision: Union[str, None] = 'c6d7e8f9a0b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_adjustment_emp_year_month', 'employee_adjustments', ['employee_id', 'year', 'month'], unique=False)
    op.create_index(op.f('ix_employee_adjustments_employee_id'), 'employee_adjustments', ['employee_id'], unique=False)
    op.create_table('loan_deductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('planned_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'year', 'month', name='uq_loan_deduction_emp_period')
    )
    op.create_index(op.f('ix_loan_deductions_employee_id'), 'loan_deductions', ['employee_id'], unique=False)
    op.add_column('employees', sa.Column('loan_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('employees', sa.Column('loan_term_months', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('loan_start_date', sa.Date(), nullable=True))
    # NB: partial unique indexes uq_period_dept_year_month / uq_period_null_dept_year_month
    # на timesheet_periods создаются вручную в прошлой миграции и автогенератору
    # не видны — НЕ трогаем их здесь.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'loan_start_date')
    op.drop_column('employees', 'loan_term_months')
    op.drop_column('employees', 'loan_amount')
    op.drop_index(op.f('ix_loan_deductions_employee_id'), table_name='loan_deductions')
    op.drop_table('loan_deductions')
    op.drop_index(op.f('ix_employee_adjustments_employee_id'), table_name='employee_adjustments')
    op.drop_index('ix_adjustment_emp_year_month', table_name='employee_adjustments')
    op.drop_table('employee_adjustments')
    # ### end Alembic commands ###
